# name: Docker Image CI

# on: 
#      workflow_dispatch
  
# #   push:
# #     branches: [ "main" ]
  
# #   pull_request:
# #     branches: [ "main" ]

  

# jobs:

#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Build the Docker image
#       run: docker build . --file Dockerfile --tag shreeshesh327/php-app
    
#     - name: Publish the Docker image
#       if: success()
#       uses: docker/login-action@v2
#       with:
#           registry: docker.io
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#           registry-endpoint: https://index.docker.io/v1/
          
#     - name: Push the Docker image
#       if: success()
#       run: |
#           docker push shreeshesh327/php-app
          
          
name: Docker Image CI

on:
   workflow_dispatch:
      inputs: 
        trigger_build:
          name: trigger_build
          description: 'Manually trigger the build job'
          required: true
          default: false
          
        trigger_login:
          name: trigger_login
          description: 'Manually trigger the login job'
          required: true
          default: false
        trigger_push:
          name: trigger_push
          description: 'Manually trigger the push job'
          required: true
          default: false


jobs:
  build:
    if: inputs.trigger_build == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag shreeshesh327/php-app
    - name: manual_build
      run: echo "Build job has been run."

  login:
    if: inputs.trigger_login == 'true' && success()
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry-endpoint: https://index.docker.io/v1/
    - name: manual_login
      run: echo "Login job has been run."

  push:
    if: inputs.trigger_push == 'true' && success()
    runs-on: ubuntu-latest
    steps:
    - name: Push Docker image
      run: docker push shreeshesh327/php-app
    
    - name: Manual push 
      run: echo "mannual push complete"


